/*
 * lis3mdl.h
 *
 *  Created on: Apr 14, 2024
 *      Author: eyalk
 */

#ifndef INC_LIS3MDL_H_
#define INC_LIS3MDL_H_

#include "stm32f7xx_hal.h"

typedef struct {
	I2C_HandleTypeDef *i2cHandle;

	float magdata[3];

} LIS3MDL_I2C;

/* I2C Address */
#define LIS3MDL_I2C_ADDR			(0x1C << 1)  /* 	I2C device address.
											ADAG LOW: Address 0x1C.
 	 	 	 	 	 	 	 	 	 	    ADAG HIGH: Address 0x1E*/
/* Who_Am_I register */
#define LIS3MDL_WHO_AM_I_VAL	0x3D
#define LIS3MDL_WHO_AM_I_ADDR	0x0F

/*
 * Register Addresses
 */

#define LIS3MDL_REG_OFFSET_X_REG_L_M		0x05
#define LIS3MDL_REG_OFFSET_X_REG_H_M		0x06
#define LIS3MDL_REG_OFFSET_Y_REG_L_M		0x07
#define LIS3MDL_REG_OFFSET_Y_REG_H_M		0x08
#define LIS3MDL_REG_OFFSET_Z_REG_L_M		0x09
#define LIS3MDL_REG_OFFSET_Z_REG_H_M		0x0A
#define LIS3MDL_REG_CTRL_REG1				0x20
#define LIS3MDL_REG_CTRL_REG2				0x21
#define LIS3MDL_REG_CTRL_REG3				0x22
#define LIS3MDL_REG_CTRL_REG4				0x23
#define LIS3MDL_REG_CTRL_REG5				0x24
#define LIS3MDL_REG_STATUS_REG				0x27
#define LIS3MDL_REG_OUT_X_L					0x28
#define LIS3MDL_REG_OUT_X_H					0x29
#define LIS3MDL_REG_OUT_Y_L					0x2A
#define LIS3MDL_REG_OUT_Y_H					0x2B
#define LIS3MDL_REG_OUT_Z_L					0x2C
#define LIS3MDL_REG_OUT_Z_H					0x2D
#define LIS3MDL_REG_OUT_L					0x2E
#define LIS3MDL_REG_OUT_H					0x2F
#define LIS3MDL_REG_INT_CFG					0x30
#define LIS3MDL_REG_INT_SRC					0x31
#define LIS3MDL_REG_THS_L					0x32
#define LIS3MDL_REG_THS_H					0x33

/* CTRL_REG1 register */
#define LIS3MDL_CTRL1_REG_ST_POS			0x00
#define LIS3MDL_CTRL1_REG_ST_DISABLE		(0x00 << LIS3MDL_CTRL1_REG_ST_POS)
#define LIS3MDL_CTRL1_REG_ST_ENABLE			(0x01 << LIS3MDL_CTRL1_REG_ST_POS)

#define LIS3MDL_CTRL1_REG_FAST_ODR_POS		0x01
#define LIS3MDL_CTRL1_REG_FAST_ODR_DISABLE	(0x00 << LIS3MDL_CTRL1_REG_FAST_ODR_POS)
#define LIS3MDL_CTRL1_REG_FAST_ODR_ENABLE	(0x01 << LIS3MDL_CTRL1_REG_FAST_ODR_POS)

#define LIS3MDL_CTRL1_REG_DO_POS			0x02
#define LIS3MDL_CTRL1_REG_DO_0_625HZ		(0x00 << LIS3MDL_CTRL1_REG_DO_POS)
#define LIS3MDL_CTRL1_REG_DO_1_25HZ			(0x01 << LIS3MDL_CTRL1_REG_DO_POS)
#define LIS3MDL_CTRL1_REG_DO_2_5HZ			(0x02 << LIS3MDL_CTRL1_REG_DO_POS)
#define LIS3MDL_CTRL1_REG_DO_5HZ			(0x03 << LIS3MDL_CTRL1_REG_DO_POS)
#define LIS3MDL_CTRL1_REG_DO_10HZ			(0x04 << LIS3MDL_CTRL1_REG_DO_POS)
#define LIS3MDL_CTRL1_REG_DO_20HZ			(0x05 << LIS3MDL_CTRL1_REG_DO_POS)
#define LIS3MDL_CTRL1_REG_DO_40HZ			(0x06 << LIS3MDL_CTRL1_REG_DO_POS)
#define LIS3MDL_CTRL1_REG_DO_80HZ			(0x07 << LIS3MDL_CTRL1_REG_DO_POS)

#define LIS3MDL_CTRL1_REG_OM_POS			0x05
#define LIS3MDL_CTRL1_REG_OM_LP				(0x00 << LIS3MDL_CTRL1_REG_OM_POS)
#define LIS3MDL_CTRL1_REG_OM_MP				(0x01 << LIS3MDL_CTRL1_REG_OM_POS)
#define LIS3MDL_CTRL1_REG_OM_HP				(0x02 << LIS3MDL_CTRL1_REG_OM_POS)
#define LIS3MDL_CTRL1_REG_OM_UHP			(0x03 << LIS3MDL_CTRL1_REG_OM_POS)

#define LIS3MDL_CTRL1_REG_TEMP_EN_POS		0x07
#define LIS3MDL_CTRL1_REG_TEMP_EN_DISABLE	(0x00 <<  LIS3MDL_CTRL1_REG_TEMP_EN_POS)
#define LIS3MDL_CTRL1_REG_TEMP_EN_ENABLE	(0x01 <<  LIS3MDL_CTRL1_REG_TEMP_EN_POS)

/* CTRL_REG2 register */
#define LIS3MDL_CTRL2_REG_SOFT_RST_POS		0x02
#define LIS3MDL_CTRL2_REG_SOFT_RST_DISABLE	(0x00 << LIS3MDL_CTRL2_REG_SOFT_RST_POS)
#define LIS3MDL_CTRL2_REG_SOFT_RST_SET		(0x01 << LIS3MDL_CTRL2_REG_SOFT_RST_POS)

#define LIS3MDL_CTRL2_REG_REBOOT_POS		0x03
#define LIS3MDL_CTRL2_REG_REBOOT_DISABLE	(0x00 << LIS3MDL_CTRL2_REG_REBOOT_POS)
#define LIS3MDL_CTRL2_REG_REBOOT_SET		(0x01 << LIS3MDL_CTRL2_REG_REBOOT_POS)

#define LIS3MDL_CTRL2_REG_FS_POS			0x05
#define LIS3MDL_CTRL2_REG_FS_4_GAUSS		(0x00 << LIS3MDL_CTRL2_REG_FS_POS)
#define LIS3MDL_CTRL2_REG_FS_8_GAUSS		(0x01 << LIS3MDL_CTRL2_REG_FS_POS)
#define LIS3MDL_CTRL2_REG_FS_12_GAUSS		(0x02 << LIS3MDL_CTRL2_REG_FS_POS)
#define LIS3MDL_CTRL2_REG_FS_16_GAUSS		(0x03 << LIS3MDL_CTRL2_REG_FS_POS)

/* CTRL_REG_3 register */
#define LIS3MDL_CTRL3_REG_MD_POS					0x00
#define LIS3MDL_CTRL3_REG_MD_CONTINUOUS_MODE		(0x00 << LIS3MDL_CTRL3_REG_MD_POS)
#define LIS3MDL_CTRL3_REG_MD_SINGLE_MODE			(0x01 << LIS3MDL_CTRL3_REG_MD_POS)
#define LIS3MDL_CTRL3_REG_MD_POWER_DOWN_MODE		(0x02 << LIS3MDL_CTRL3_REG_MD_POS)
#define LIS3MDL_CTRL3_REG_MD_POWER_DOWN_MODE2		(0x03 << LIS3MDL_CTRL3_REG_MD_POS)

#define LIS3MDL_CTRL3_REG_SIM_POS			0x02
#define LIS3MDL_CTRL3_REG_SIM_SPI_4WIRE		(0x00 << LIS3MDL_CTRL3_REG_SIM_POS)
#define LIS3MDL_CTRL3_REG_SIM_SPI_3WIRE		(0x01 << LIS3MDL_CTRL3_REG_SIM_POS)

#define LIS3MDL_CTRL3_REG_LP_POS			0x05
#define LIS3MDL_CTRL3_REG_LP_DISABLE		(0x00 << LIS3MDL_CTRL3_REG_LP_POS)
#define LIS3MDL_CTRL3_REG_LP_ENABLE			(0x01 << LIS3MDL_CTRL3_REG_LP_POS)

/* CTRL_REG4 register */
#define LIS3MDL_CTRL4_REG_BLE_POS			0x01
#define LIS3MDL_CTRL4_REG_BLE_LITTLE_END	(0x00 << LIS3MDL_CTRL4_REG_BLE_POS)
#define LIS3MDL_CTRL4_REG_BLE_BIG_END		(0x01 << LIS3MDL_CTRL4_REG_BLE_POS)

#define LIS3MDL_CTRL4_REG_OMZ_POS			0x02
#define LIS3MDL_CTRL4_REG_OMZ_LP			(0x00 << LIS3MDL_CTRL4_REG_OMZ_POS)
#define LIS3MDL_CTRL4_REG_OMZ_MP			(0x01 << LIS3MDL_CTRL4_REG_OMZ_POS)
#define LIS3MDL_CTRL4_REG_OMZ_HP			(0x02 << LIS3MDL_CTRL4_REG_OMZ_POS)
#define LIS3MDL_CTRL4_REG_OMZ_UHP			(0x03 << LIS3MDL_CTRL4_REG_OMZ_POS)

/* CTRL_REG5  register */
#define LIS3MDL_CTRL4_REG_BDU_POS						0x06
#define LIS3MDL_CTRL4_REG_BDU_CONT_UPDATE				(0x00 << LIS3MDL_CTRL4_REG_BLE_POS)
#define LIS3MDL_CTRL4_REG_BDU_BLOCK_UNTIL_READ_UPDATE	(0x01 << LIS3MDL_CTRL4_REG_BLE_POS)


/*
 * General Functions
 */

HAL_StatusTypeDef LIS3MDL_Init(LIS3MDL_I2C* dev, I2C_HandleTypeDef* pHI2C);

/*
 * Register Operations
 */

HAL_StatusTypeDef LIS3MDL_I2C_ReadRegister(LIS3MDL_I2C *dev, uint8_t reg, uint8_t* data);
HAL_StatusTypeDef LIS3MDL_I2C_ReadRegisters(LIS3MDL_I2C *dev, uint8_t reg, uint8_t *data, uint8_t length);
HAL_StatusTypeDef LIS3MDL_I2C_WriteRegister(LIS3MDL_I2C *dev, uint8_t reg, uint8_t *data);

#endif /* INC_LIS3MDL_H_ */
