/*
 * lsm6dsox.h
 *
 *  Created on: Mar 26, 2024
 *      Author: eyalk
 */

#ifndef INC_LSM6DSOX_H_
#define INC_LSM6DSOX_H_

#include "stm32f7xx_hal.h" /* For I2C & SPI  */


/*
 * Constants Defines
 */

#define G_ACC				(9.81)
#define GYRO_DPS_TO_LSB		(0.0175)

/*
 * Defines
 */

#define LSM6DSOX_I2C_ADDR	(0x6A << 1) 	/* 	I2C device address.
											ADAG LOW: Address 0x6A.
 	 	 	 	 	 	 	 	 	 	    ADAG HIGH: Address 0x6B*/
#define LSM6DSOX_WHO_AM_I_VAL	0x6C


/*
 * Register Addresses
 */

#define LSM6DSOX_REG_FUN_CFG_ACCESS 			0x01
#define LSM6DSOX_REG_PIN_CTRL 					0x02
#define LSM6DSOX_REG_S4S_TPH_L					0x04
#define LSM6DSOX_REG_S4S_TPH_H					0x05
#define LSM6DSOX_REG_S4S_RR						0x06
#define LSM6DSOX_REG_FIFO_CTRL1					0x07
#define LSM6DSOX_REG_FIFO_CTRL2					0x08
#define LSM6DSOX_REG_FIFO_CTRL3					0x09
#define LSM6DSOX_REG_FIFO_CTRL4					0x0A
#define LSM6DSOX_REG_COUNTER_BDR_REG1			0x0B
#define LSM6DSOX_REG_COUNTER_BDR_REG2			0x0C
#define LSM6DSOX_REG_INT1_CTRL					0x0D
#define LSM6DSOX_REG_INT2_CTRL      			0x0E
#define LSM6DSOX_REG_WHO_AM_I					0x0F
#define LSM6DSOX_REG_CTRL1_XL					0x10
#define LSM6DSOX_REG_CTRL2_G					0x11
#define LSM6DSOX_REG_CTRL3_C					0x12
#define LSM6DSOX_REG_CTRL4_C					0x13
#define LSM6DSOX_REG_CTRL5_C					0x14
#define LSM6DSOX_REG_CTRL6_C					0x15
#define LSM6DSOX_REG_CTRL7_G					0x16
#define LSM6DSOX_REG_CTRL8_XL					0x17
#define LSM6DSOX_REG_CTRL9_XL					0x18
#define LSM6DSOX_REG_CTRL10_C					0x19
#define LSM6DSOX_REG_ALL_INT_SRC				0x1A
#define LSM6DSOX_REG_WAKE_UP_SRC				0x1B
#define LSM6DSOX_REG_TAP_SRC					0x1C
#define LSM6DSOX_REG_D9D_SRC					0x1D
#define LSM6DSOX_REG_STATUS_REG					0x1E
#define LSM6DSOX_REG_OUT_TEMP_L					0x20
#define LSM6DSOX_REG_OUT_TEMP_H					0x21
#define LSM6DSOX_REG_OUTX_L_G					0x22
#define LSM6DSOX_REG_OUTX_H_G					0x23
#define LSM6DSOX_REG_OUTY_L_G					0x24
#define LSM6DSOX_REG_OUTY_H_G					0x25
#define LSM6DSOX_REG_OUTZ_L_G					0x26
#define LSM6DSOX_REG_OUTZ_H_G					0x27
#define LSM6DSOX_REG_OUTX_L_A					0x28
#define LSM6DSOX_REG_OUTX_H_A					0x29
#define LSM6DSOX_REG_OUTY_L_A					0x2A
#define LSM6DSOX_REG_OUTY_H_A					0x2B
#define LSM6DSOX_REG_OUTZ_L_A					0x2C
#define LSM6DSOX_REG_OUTZ_H_A					0x2D
#define LSM6DSOX_REG_EMB_FUN_STATUS_MAINPAGE	0x35
#define LSM6DSOX_REG_FSM_STATUS_A_MAINPAGE		0x36
#define LSM6DSOX_REG_FSM_STATUS_B_MAINPAGE		0x37
#define LSM6DSOX_REG_MLC_STATUS_MAINPAGE		0x38
#define LSM6DSOX_REG_STATUS_MASTER_MAINPAGE		0x39
#define LSM6DSOX_REG_FIFO_STATUS1				0x3A
#define LSM6DSOX_REG_FIFO_STATUS2				0x3B
#define LSM6DSOX_REG_TIMESTAMP0					0x40
#define LSM6DSOX_REG_TIMESTAMP1					0x41
#define LSM6DSOX_REG_TIMESTAMP2					0x42
#define LSM6DSOX_REG_TIMESTAMP3					0x43
#define LSM6DSOX_REG_UI_STATUS_REG_OIS			0x49
#define LSM6DSOX_REG_UI_OUTX_L_G_OIS			0x4A
#define LSM6DSOX_REG_UI_OUTX_H_G_OIS			0x4B
#define LSM6DSOX_REG_UI_OUTY_L_G_OIS			0x4C
#define LSM6DSOX_REG_UI_OUTY_H_G_OIS			0x4D
#define LSM6DSOX_REG_UI_OUTZ_L_G_OIS			0x4E
#define LSM6DSOX_REG_UI_OUTZ_H_G_OIS			0x4F
#define LSM6DSOX_REG_UI_OUTX_L_A_OIS			0x50
#define LSM6DSOX_REG_UI_OUTX_H_A_OIS			0x51
#define LSM6DSOX_REG_UI_OUTY_L_A_OIS			0x52
#define LSM6DSOX_REG_UI_OUTY_H_A_OIS			0x53
#define LSM6DSOX_REG_UI_OUTZ_L_A_OIS			0x54
#define LSM6DSOX_REG_UI_OUTZ_H_A_OIS			0x55
#define LSM6DSOX_REG_TAP_CFG0					0x56
#define LSM6DSOX_REG_TAP_CFG1					0x57
#define LSM6DSOX_REG_TAP_CFG2					0x58
#define LSM6DSOX_REG_TAP_THS_6D					0x59
#define LSM6DSOX_REG_INT_DUR2					0x5A
#define LSM6DSOX_REG_WAKE_UP_THS				0x5B
#define LSM6DSOX_REG_WAKE_UP_DUR				0x5C
#define LSM6DSOX_REG_FREE_FALL					0x5D
#define LSM6DSOX_REG_MD1_CFG					0x5E
#define LSM6DSOX_REG_MD2_CFG					0x5F
#define LSM6DSOX_REG_S4S_ST_CMD_CODE			0x60
#define LSM6DSOX_REG_S4S_DT_REG					0x61
#define LSM6DSOX_REG_I3C_BUS_AVB				0x62
#define LSM6DSOX_REG_INTERNAL_FREQ_FINE			0x63
#define LSM6DSOX_REG_UI_INT_OIS					0x6F
#define LSM6DSOX_REG_UI_CTRL1_OIS				0x70
#define LSM6DSOX_REG_UI_CTRL2_OIS				0x71
#define LSM6DSOX_REG_UI_CTRL3_OIS				0x72
#define LSM6DSOX_REG_X_OFS_USR					0x73
#define LSM6DSOX_REG_Y_OFS_USR					0x74
#define LSM6DSOX_REG_Z_OFS_USR					0x75
#define LSM6DSOX_REG_FIFO_DATA_OUT_TAG			0x78
#define LSM6DSOX_REG_FIFO_DATA_X_L				0x79
#define LSM6DSOX_REG_FIFO_DATA_X_H				0x7A
#define LSM6DSOX_REG_FIFO_DATA_Y_L				0x7B
#define LSM6DSOX_REG_FIFO_DATA_Y_H				0x7C
#define LSM6DSOX_REG_FIFO_DATA_Z_L				0x7D
#define LSM6DSOX_REG_FIFO_DATA_Z_H				0x7E

/*
 * Accelerometer CTRL
 */

/*   SPEED CONFIGURATION    */
#define LSM6DSOX_CTRL1_XL_ODR_POS				4
#define LSM6DSOX_CTRL1_XL_SPEED_416HZ			( 0x06 << LSM6DSOX_CTRL1_XL_ODR_POS )
#define LSM6DSOX_CTRL1_XL_SPEED_833HZ			( 0x07 << LSM6DSOX_CTRL1_XL_ODR_POS )
#define LSM6DSOX_CTRL1_XL_SPEED_1_66KHZ			( 0x08 << LSM6DSOX_CTRL1_XL_ODR_POS )
#define LSM6DSOX_CTRL1_XL_SPEED_3_33KHZ			( 0x09 << LSM6DSOX_CTRL1_XL_ODR_POS )
#define LSM6DSOX_CTRL1_XL_SPEED_6_66KHZ			( 0x0A << LSM6DSOX_CTRL1_XL_ODR_POS )

/*   LPF CONFIGURATION   */
#define LSM6DSOX_CTRL1_XL_LPF_POS				0
#define LSM6DSOX_CTRL1_XL_LPF_DISABLE			( 0x00 << LSM6DSOX_CTRL1_XL_LPF_POS)
#define LSM6DSOX_CTRL1_XL_LPF_ENABLE			( 0x01 << LSM6DSOX_CTRL1_XL_LPF_POS)

/*   SCALE CONFIGURATION   */
#define LSM6DSOX_CTRL1_XL_SCALE_POS				2
#define LSM6DSOX_CTRL1_XL_SCALE_2G				( 0 << LSM6DSOX_CTRL1_XL_SCALE_POS )
#define LSM6DSOX_CTRL1_XL_SCALE_2G_DONT_USE		( 1 << LSM6DSOX_CTRL1_XL_SCALE_POS )
#define LSM6DSOX_CTRL1_XL_SCALE_4G				( 2 << LSM6DSOX_CTRL1_XL_SCALE_POS )
#define LSM6DSOX_CTRL1_XL_SCALE_8G				( 3 << LSM6DSOX_CTRL1_XL_SCALE_POS )


/*
 * Gyroscope CTRL
 */

/*   SPEED CONFIGURATION   */
#define LSM6DSOX_CTRL2_G_ODR_POS				4
#define LSM6DSOX_CTRL2_G_SPEED_1_66KHZ			( 0x08 << LSM6DSOX_CTRL2_G_ODR_POS )
#define LSM6DSOX_CTRL2_G_SPEED_3_33KHZ			( 0x09 << LSM6DSOX_CTRL2_G_ODR_POS )
#define LSM6DSOX_CTRL2_G_SPEED_6_66KHZ			( 0x0A << LSM6DSOX_CTRL2_G_ODR_POS )

/*   SCALE CONFIGURATION   */
#define LSM6DSOX_CTRL2_G_FS_POS					2
#define LSM6DSOX_CTRL2_G_FS_250					( 0 << LSM6DSOX_CTRL2_G_FS_POS )
#define LSM6DSOX_CTRL2_G_FS_500					( 1 << LSM6DSOX_CTRL2_G_FS_POS )
#define LSM6DSOX_CTRL2_G_FS_1000				( 2 << LSM6DSOX_CTRL2_G_FS_POS )
#define LSM6DSOX_CTRL2_G_FS_2000				( 3 << LSM6DSOX_CTRL2_G_FS_POS )

/*   ODR CONFIGURATION   */
#define LSM6DSOX_CTRL2_G_ODR_POS				4
#define LSM6DSOX_CTRL2_G_ODR_12_5HZ				( 1 << LSM6DSOX_CTRL2_G_ODR_POS )
#define LSM6DSOX_CTRL2_G_ODR_26HZ				( 2 << LSM6DSOX_CTRL2_G_ODR_POS )
#define LSM6DSOX_CTRL2_G_ODR_52HZ				( 3 << LSM6DSOX_CTRL2_G_ODR_POS )
#define LSM6DSOX_CTRL2_G_ODR_104HZ				( 4 << LSM6DSOX_CTRL2_G_ODR_POS )
#define LSM6DSOX_CTRL2_G_ODR_208HZ				( 5 << LSM6DSOX_CTRL2_G_ODR_POS )
#define LSM6DSOX_CTRL2_G_ODR_416HZ				( 6 << LSM6DSOX_CTRL2_G_ODR_POS )
#define LSM6DSOX_CTRL2_G_ODR_833HZ				( 7 << LSM6DSOX_CTRL2_G_ODR_POS )
#define LSM6DSOX_CTRL2_G_ODR_1_66KHZ			( 8 << LSM6DSOX_CTRL2_G_ODR_POS )
#define LSM6DSOX_CTRL2_G_ODR_3_33KHZ			( 9 << LSM6DSOX_CTRL2_G_ODR_POS )
#define LSM6DSOX_CTRL2_G_ODR_6_66KHZ			( 10 << LSM6DSOX_CTRL2_G_ODR_POS )

/*   SCALE 125dps CONFIGURATION   */
/* Disabling this makes the gyro select its scale through
 * the FS[1:0] bits
 */
#define LSM6DSOX_CTRL2_G_FS125_POS				1
#define LSM6DSOX_CTRL2_G_FS125_DISABLE			(0x00 << LSM6DSOX_CTRL2_G_FS125_POS)
#define LSM6DSOX_CTRL2_G_FS125_ENABLE			(0x01 << LSM6DSOX_CTRL2_G_FS125_POS)

/*
 * FIFO CTRL
 */

/*   FIFO CTRL4   */
#define LSM6DSOX_FIFO_CTRL4_FIFO_MODE0_POS				0




/*
 * General CONFIGURATION
 */

/* CTRL3_C Register */
#define LSM6DSOX_CTRL3_C_SW_RESET				(0x01)

#define LSM6DSOX_CTRL3_C_IF_INC_POS				2
#define LSM6DSOX_CTRL3_C_IF_INC_DISABLE			(0x00 << LSM6DSOX_CTRL3_C_IF_INC_POS)
#define LSM6DSOX_CTRL3_C_IF_INC_ENABLE			(0x01 << LSM6DSOX_CTRL3_C_IF_INC_POS)

#define LSM6DSOX_CTRL3_C_BDU_POS				6
#define LSM6DSOX_CTRL3_C_BDU_DISABLE			(0x00 << LSM6DSOX_CTRL3_C_BDU_POS)
#define LSM6DSOX_CTRL3_C_BDU_ENABLE				(0x01 << LSM6DSOX_CTRL3_C_BDU_POS)

/* CTRL4_C Register */
#define LSM6DSOX_CTRL4_C_LPF_SEL_G_POS			1
#define LSM6DSOX_CTRL4_C_LPF_SEL_G_DISABLE		(0x00 << LSM6DSOX_CTRL4_C_LPF_SEL_G_POS)
#define LSM6DSOX_CTRL4_C_LPF_SEL_G_ENABLE		(0x01 << LSM6DSOX_CTRL4_C_LPF_SEL_G_POS)

#define LSM6DSOX_CTRL4_C_I2C_DISABLE_POS		2
#define LSM6DSOX_CTRL4_C_I2C_DISABLE_DISABLE	(0x00 << LSM6DSOX_CTRL4_C_I2C_DISABLE_POS)
#define LSM6DSOX_CTRL4_C_I2C_DISABLE_ENABLE		(0x01 << LSM6DSOX_CTRL4_C_I2C_DISABLE_POS)

#define LSM6DSOX_CTRL4_C_DRDY_MASK_POS			3
#define LSM6DSOX_CTRL4_C_DRDY_MASK_DISABLE		(0x00 << LSM6DSOX_CTRL4_C_DRDY_MASK_POS)
#define LSM6DSOX_CTRL4_C_DRDY_MASK_ENABLE		(0x01 << LSM6DSOX_CTRL4_C_DRDY_MASK_POS)

/* CTRL5_C Registerr */
#define LSM6DSOX_CTRL5_C_XL_UL_EN_POS			7
#define LSM6DSOX_CTRL5_C_XL_UL_EN_DISABLE		(0x00 << LSM6DSOX_CTRL5_C_XL_UL_EN_POS)
#define LSM6DSOX_CTRL5_C_XL_UL_EN_ENABLE		(0x01 << LSM6DSOX_CTRL5_C_XL_UL_EN_POS)

//Self-test needed?

/* CTRL6_C Register */
#define LSM6DSOX_CTRL6_C_FTYPE_POS				0

#define LSM6DSOX_CTRL6_C_USR_OFF_W_POS			3

#define LSM6DSOX_CTRL6_C_XL_HM_MODE_POS			4
#define LSM6DSOX_CTRL6_C_XL_HM_MODE_DISABLE		(0x00 << LSM6DSOX_CTRL6_C_XL_HM_MODE_POS)
#define LSM6DSOX_CTRL6_C_XL_HM_MODE_ENABLE		(0x01 << LSM6DSOX_CTRL6_C_XL_HM_MODE_POS)

/* CRT7_C Register */
#define LSM6DSOX_CTRL7_G_OIS_ON_POS				0
#define LSM6DSOX_CTRL7_G_OIS_ON_DISABLE			(0x00 <<  LSM6DSOX_CTRL7_G_OIS_ON_POS)
#define LSM6DSOX_CTRL7_G_OIS_ON_ENABLE			(0x01 <<  LSM6DSOX_CTRL7_G_OIS_ON_POS)

#define LSM6DSOX_CTRL7_USR_OFF_ON_OUT_POS		1

#define LSM6DSOX_CTRL7_OIS_ON_EN_POS			2

#define LSM6DSOX_CTRL7_G_HPM_G_POS				4
#define LSM6DSOX_CTRL7_G_HPM_G_16mHZ			(0 <<  LSM6DSOX_CTRL7_G_HPM_G_POS)
#define LSM6DSOX_CTRL7_G_HPM_G_65mHZ			(1 <<  LSM6DSOX_CTRL7_G_HPM_G_POS)
#define LSM6DSOX_CTRL7_G_HPM_G_260mHZ			(2 <<  LSM6DSOX_CTRL7_G_HPM_G_POS)
#define LSM6DSOX_CTRL7_G_HPM_G_1_04HZ			(3 <<  LSM6DSOX_CTRL7_G_HPM_G_POS)

#define LSM6DSOX_CTRL7_G_HP_EN_G_POS			6
#define LSM6DSOX_CTRL7_G_HP_EN_G_DISABLE		(0 <<  LSM6DSOX_CTRL7_G_HP_EN_G_POS)
#define LSM6DSOX_CTRL7_G_HP_EN_G_ENABLE			(1 <<  LSM6DSOX_CTRL7_G_HP_EN_G_POS)

#define LSM6DSOX_CTRL7_G_G_HM_MODE_POS			7
#define LSM6DSOX_CTRL7_G_G_HM_MODE_DISABLE		(0x00 <<  LSM6DSOX_CTRL7_G_HP_EN_G_POS)
#define LSM6DSOX_CTRL7_G_G_HM_MODE_ENABLE		(0x01 <<  LSM6DSOX_CTRL7_G_HP_EN_G_POS)

/*  CTRL8_XL Register */
#define LSM6DSOX_CTRL8_XL_LOW_PASS_ON_6D_POS	0



/*
 * OUTPUT REGISTERS
 */
#define LSM6DSOX_STATUS_REG_XLDA_GET			0
#define LSM6DSOX_STATUS_REG_GDA_GET				1
#define LSM6DSOX_STATUS_REG_TDA_GET				2

/*   TEMPERATURE DATA   */
#define LSM6DSOX_CONST_TEMP_SENSITIVITY_LSB_TO_C			256
#define LSM6DSOX_CONST_TEMP_SENSITIVITY_C_TO_LSB			0.00390625f
#define LSM6DSOX_CONST_TEMP_VAL_AT_0_LSB					25.0f

/*   CALIBRATION DATA   */
#define LSM6DSOX_GYRO_CALIB_CONST_X		0.0
#define LSM6DSOX_GYRO_CALIB_CONST_Y		0.1
#define LSM6DSOX_GYRO_CALIB_CONST_Z		-0.45


/*
 * Sensor Data Struct
 */

typedef struct {

	//  I2C handler
	I2C_HandleTypeDef *i2cHandle;

	// Acceleration data(X,Y,Z) in m/s^2
	uint8_t acc_full_scale_range;
	float acc_scale_resolution;
	float acc_FS_to_scale;
	float acc_data_mps2[3];

	// Temperature data in C
	float temp_c;

	//Gyrometer data(Roll, Pitch, .. ) in deg/s?
	uint16_t angular_rate_sensitivity;
	float angular_mdps_to_scale;
	float angular_rate_dps[3]; // [pitch, roll, yaw]

} LSM6DSOX_I2C;

uint8_t LSM6DSOX_I2C_init(LSM6DSOX_I2C *dev, I2C_HandleTypeDef *pHI2C);

/*
 * Data Acquisition
 */

HAL_StatusTypeDef LSM6DSOX_I2C_ReadTemp(LSM6DSOX_I2C *dev);
HAL_StatusTypeDef LSM6DSOX_I2C_ReadAccel(LSM6DSOX_I2C *dev);
HAL_StatusTypeDef LSM6DSOX_I2C_ReadGyro(LSM6DSOX_I2C *dev);

/*
 * Register Operations
 */

HAL_StatusTypeDef LSM6DSOX_I2C_ReadRegister(LSM6DSOX_I2C *dev, uint8_t reg, uint8_t* data);
HAL_StatusTypeDef LSM6DSOX_I2C_ReadRegisters(LSM6DSOX_I2C *dev, uint8_t reg, uint8_t *data, uint8_t length);
HAL_StatusTypeDef LSM6DSOX_I2C_WriteRegister(LSM6DSOX_I2C *dev, uint8_t reg, uint8_t *data);

#endif /* INC_LSM6DSOX_H_ */
